export default {
  name: 'content',
  type: 'array',
  title: 'Komponenty podstrony',
  of: [
    {type: 'HeroApplication'},
    {type: 'CaseStudy'},
    {type: 'Comparison'},
    {type: 'Features'},
    {type: 'StatsGrid'},
    {type: 'ListWithIconAndCta'},
    {type: 'Reviews'},
    {type: 'FloatingTilesAndImages'},
    {type: 'Faq'},
    {type: 'Contact'},
    {type: 'Steps'},
    {type: 'Team'},
    {type: 'PersonIntroduction'},
    {type: 'FloatingItems'},
  ],
}
